### ISSUE TITLE
Comp inspiration for our dashboard and app

### ISSUE THREAD

**Issue by jordan-sullivan** [kpn678/fitlit#3]

**Comment by jordan-sullivan** [comment]
We like the streamlined images rather than so many words. We will aim to use icons in our app like this examples [.[](url)<img width="481" alt="image" src="https://user-images.githubusercontent.com/95270427/168440460-23999fa8-c622-4fce-b6a3-60e9192091ef.png">

**Comment by kpn678** [comment]
Link: https://dribbble.com/shots/14973430-Fitness-Tracker-Dashboard/attachments/6692900?mode=media
<img width="500" alt="Screen Shot 2022-05-14 at 10 25 17" src="https://user-images.githubusercontent.com/99382481/168440405-5fe58c56-49c5-4c8a-b13c-0242adc48664.png">

From this dashboard example, I like the simplicity and intuitive format. The brightness of the background and colors is also appealing. The 3 boxes at the bottom can each display simple data for activity, hydration, and sleep. The side navigation bar can allow a user to click on a type of data to display more information.

**Comment by GrantXBeard** [comment]
In this example we liked the different sized widgets and the line graph. We plan to have more organizational aspects.
![original-09202c4f7a850bb6e7b9024006f1ea1c Small](https://user-images.githubusercontent.com/96991108/168440589-6b76d886-45b4-412b-8d73-75c7c9834995.jpeg)
