### ISSUE TITLE
Look into 3rd party libraries

### ISSUE THREAD

**Issue by kpn678** [kpn678/fitlit#6]

**Comment by jordan-sullivan** [comment]
Hey Team, I looked into both of the third party libraries and...they look awesome and not too terribly difficult to use! I think if we pick one to use it will really help us format our date and time, or make beautiful charts! (I'm leaning towards charts if I have to pick one). I think we could def conquer one together. I found 2 really helpful and clear videos if you haven't  looked yet.  Excited to chat at 1pm tomorrow to hear your thoughts. The line graph example towards the end of the chard vid looked sooo good!
Day.JS: https://www.youtube.com/watch?v=vzGzys3enCE
Chart.JS: https://www.youtube.com/watch?v=sE08f4iuOhA

**Comment by GrantXBeard** [comment]
I talked to my dev friend and he said he uses day.js all the time and its super useful. He also said chart.js is great so I think it's a good idea to try both.

**Comment by kpn678** [comment]
Yes, I agree, watching both videos makes me realize we will most likely need both at some point anyhow.
